version: 0.2

env:
  variables:
    # --- set these as CodeBuild environment variables (UI or pipeline) ---
    TF_BUCKET: "502768277707-terraform-state-bucket"           # your remote state bucket
    TF_KEY: "state/terraform.tfstate"                           # path inside the bucket (no s3://)
    TF_REGION: "ca-central-1"                                   # backend + AWS region
    CLUSTER_NAME: "curious-rock-crab"                           # your EKS cluster name
    K8S_NAMESPACE: "default"                                    # target namespace
    DEPLOYMENT_NAME: "flask-app"                                # app/deployment name
    IMAGE_URI: "502768277707.dkr.ecr.ca-central-1.amazonaws.com/aws_python_app:latest"
    # ---------------------------------------------------------------------

phases:
  install:
    commands:
      - echo "Installing Terraform"
      - curl -sSLo terraform.zip "https://releases.hashicorp.com/terraform/1.13.0/terraform_1.13.0_linux_amd64.zip"
      - unzip -o terraform.zip -d /usr/local/bin && rm -f terraform.zip
      - terraform -version
  pre_build:
    commands:
      - echo "Prepare working dir"
      - cd terraform
  build:
    commands:
      - echo "Terraform init (S3 backend)"
      - terraform init -input=false \
          -backend-config="bucket=${TF_BUCKET}" \
          -backend-config="key=${TF_KEY}" \
          -backend-config="region=${TF_REGION}"

      - echo "Terraform validate"
      - terraform validate

      - echo "Terraform plan"
      - terraform plan -input=false -out=tfplan \
          -var="region=${TF_REGION}" \
          -var="cluster_name=${CLUSTER_NAME}" \
          -var="namespace=${K8S_NAMESPACE}" \
          -var="app_name=${DEPLOYMENT_NAME}" \
          -var="image=${IMAGE_URI}"
  post_build:
    commands:
      - echo "Terraform apply"
      - terraform apply -auto-approve tfplan
      - echo "Outputs (if any):"
      - terraform output || true

artifacts:
  files:
    - '**/*'
  discard-paths: yes

cache:
  paths:
    - 'terraform/.terraform/**/*'
