apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  labels:
    app: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: 502768277707.dkr.ecr.ca-central-1.amazonaws.com/aws_python_app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: FLASK_ENV
              value: production
          readinessProbe:
            httpGet:
              path: /healthz           # use "/" if that's your real endpoint
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz           # use "/" if that's your real endpoint
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 20
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"