apiVersion: v1
kind: Service
metadata:
  name: flask-app
  labels: { app: flask-app }
spec:
  type: LoadBalancer
  selector:
    app: flask-app
  ports:
  - name: http
    port: 80
    targetPort: 8000